services:
  backend:
    build: ./backend
    ports:
      - "${MOOCORN_BACKEND_PORT:-8888}:8888"
    volumes:
      - ./backend/data:/app/data
    environment:
      - LLM_BASE_URL=${DOCKER_LLM_BASE_URL:-http://host.docker.internal:11434/v1}
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_MODEL=${LLM_MODEL:-phi}
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - __pycache__/
            - .pytest_cache/
            - data/images/
            - data/sessions.csv
            - "*.log"
            - .venv/
            - "*.pyc"
            - "**/__pycache__/"
        - action: rebuild
          path: ./backend/pyproject.toml
        - action: rebuild
          path: ./backend/Dockerfile
        - action: rebuild
          path: ./docker-compose.yml

  frontend:
    build: ./frontend
    ports:
      - "${MOOCORN_FRONTEND_PORT:-5173}:5173"
    environment:
      - VITE_MOOCORN_API_URL=http://backend:8888
      - VITE_CAMERA_MAX_WIDTH=${VITE_CAMERA_MAX_WIDTH:-1024}
      - VITE_CAMERA_MAX_HEIGHT=${VITE_CAMERA_MAX_HEIGHT:-768}
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: ./frontend/package.json
        - action: rebuild
          path: ./frontend/pnpm-lock.yaml
        - action: rebuild
          path: ./frontend/Dockerfile
        - action: rebuild
          path: ./docker-compose.yml