[project]
name = "moocorn-backend"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "opencv-python-headless",
    "numpy",
    "python-multipart",
    "openai",
    "aiofiles",
]
