name: Docker Compose Build

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'docker-compose.yml'
      - 'backend/Dockerfile'
      - 'frontend/Dockerfile'
      - '.github/workflows/docker-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'docker-compose.yml'
      - 'backend/Dockerfile'
      - 'frontend/Dockerfile'
      - '.github/workflows/docker-build.yml'

env:
  MOOCORN_BACKEND_PORT: ${{ vars.MOOCORN_BACKEND_PORT || '8888' }}
  MOOCORN_FRONTEND_PORT: ${{ vars.MOOCORN_FRONTEND_PORT || '5173' }}
  VITE_CAMERA_MAX_WIDTH: ${{ vars.VITE_CAMERA_MAX_WIDTH || '1024' }}
  VITE_CAMERA_MAX_HEIGHT: ${{ vars.VITE_CAMERA_MAX_HEIGHT || '768' }}

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build with Docker Compose
      run: docker compose build

    - name: Test services start
      run: |
        docker compose up -d
        sleep 10
        docker compose ps
        docker compose logs

    - name: Cleanup
      if: always()
      run: docker compose down